In [2]:
#pandas are used for working with data sets (data analysis)
import pandas as pd
x = [1,2,3,4,5]
var = pd.Series(x)
print(var)
print(type(var))
print(var[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
3


C:\Users\Riddhi\AppData\Local\Temp\ipykernel_2440\485943888.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
x = [1,2,3]
var = pd.Series(x,index=['a','b','c'],dtype="f",name="python")
print(var)

a    1.0
b    2.0
c    3.0
Name: python, dtype: float32


In [4]:
dic = {"name":['python','c','c++','java'],"rank":[1,2,3,4]}
var = pd.Series(dic)
print(var)

name    [python, c, c++, java]
rank              [1, 2, 3, 4]
dtype: object


In [5]:
s1 = pd.Series(12,index=[1,2,3,4])
print(s1)
print()
s2 = pd.Series(12,index=[1,2])
print(s2)
print()
print(s1+s2)

1    12
2    12
3    12
4    12
dtype: int64

1    12
2    12
dtype: int64

1    24.0
2    24.0
3     NaN
4     NaN
dtype: float64


In [6]:
x = [1,2,3,4,5]
var = pd.DataFrame(x)
print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
<class 'pandas.core.frame.DataFrame'>


In [7]:
dic = {"name":['python','c','c++','java'],"rank":[1,2,3,4]}
var = pd.DataFrame(dic)
print(var)
print()
var1 = pd.DataFrame(dic,columns=["name"])
print(var1)
print()
print("Printing particular data: ",var["name"][2])

     name  rank
0  python     1
1       c     2
2     c++     3
3    java     4

     name
0  python
1       c
2     c++
3    java

Printing particular data:  c++


In [8]:
l = [[1,2,3,4],[5,6,7,8]]
var = pd.DataFrame(l)
print(var)
print(type(var))

   0  1  2  3
0  1  2  3  4
1  5  6  7  8
<class 'pandas.core.frame.DataFrame'>


In [9]:
sr = {"s":pd.Series([1,2,3,4]),"r":pd.Series([1,2,3,4])}
print(pd.DataFrame(sr))

   s  r
0  1  1
1  2  2
2  3  3
3  4  4


In [10]:
var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var["C"] = var["A"] + var["B"]
print(var)

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12


In [11]:
var["Python"] = var["A"] < 3
print(var)

   A  B   C  Python
0  1  5   6    True
1  2  6   8    True
2  3  7  10   False
3  4  8  12   False


In [12]:
var = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var.insert(1,"python",["a","b","c","d"])
print(var)

   A python  B
0  1      a  5
1  2      b  6
2  3      c  7
3  4      d  8


In [13]:
var1 = pd.DataFrame({"A":[1,2,3,4],"B":[5,6,7,8]})
var1["num"] = var1["A"][:2]
print(var1)

   A  B  num
0  1  5  1.0
1  2  6  2.0
2  3  7  NaN
3  4  8  NaN


In [14]:
var1.pop("B")
print(var1)

   A  num
0  1  1.0
1  2  2.0
2  3  NaN
3  4  NaN


In [15]:
del var1["num"]
print(var1)

   A
0  1
1  2
2  3
3  4


In [16]:
dic = {"a":[1,2,3,4,5],"b":[1,2,3,4,5],"c":[1,2,3,4,5]}
x = pd.DataFrame(dic)
print(x)
#x.to_csv("text_new.csv")
x.to_csv("text_new1.csv",index=False,header=["First","Second","Third"])

   a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5


In [17]:
csv_1 = pd.read_csv("D:\\Data Analytst\pandas\\text_new.csv")
print(csv_1)

   Unnamed: 0  a  b  c
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3
3           3  4  4  4
4           4  5  5  5


In [18]:
csv_1 = pd.read_csv("D:\\Data Analytst\pandas\\text_new.csv",nrows=3)
print(csv_1)
print()
csv_2 = pd.read_csv("D:\\Data Analytst\pandas\\text_new.csv",usecols=["a","b"])
print(csv_2)

   Unnamed: 0  a  b  c
0           0  1  1  1
1           1  2  2  2
2           2  3  3  3

   a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5


In [19]:
csv_3 = pd.read_csv("D:\\Data Analytst\pandas\\text_new.csv",skiprows=[2])
print(csv_3)
print()
csv_4 = pd.read_csv("D:\\Data Analytst\pandas\\text_new.csv", index_col=["a"])
print(csv_4)
print()
csv_5 = pd.read_csv("D:\\Data Analytst\pandas\\text_new.csv",names=["col1","col2","col3"])
print(csv_5)

   Unnamed: 0  a  b  c
0           0  1  1  1
1           2  3  3  3
2           3  4  4  4
3           4  5  5  5

   Unnamed: 0  b  c
a                  
1           0  1  1
2           1  2  2
3           2  3  3
4           3  4  4
5           4  5  5

    col1 col2 col3
NaN    a    b    c
0.0    1    1    1
1.0    2    2    2
2.0    3    3    3
3.0    4    4    4
4.0    5    5    5


In [20]:
csvfile_1 = pd.read_csv("D:\\Data Analytst\pandas\\text_new1.csv")
print(csvfile_1)
print()
print(csvfile_1.index)
print()
print(csvfile_1.columns)
print()
print(csvfile_1.describe())

   First  Second  Third
0      1       1      1
1      2       2      2
2      3       3      3
3      4       4      4
4      5       5      5

RangeIndex(start=0, stop=5, step=1)

Index(['First', 'Second', 'Third'], dtype='object')

          First    Second     Third
count  5.000000  5.000000  5.000000
mean   3.000000  3.000000  3.000000
std    1.581139  1.581139  1.581139
min    1.000000  1.000000  1.000000
25%    2.000000  2.000000  2.000000
50%    3.000000  3.000000  3.000000
75%    4.000000  4.000000  4.000000
max    5.000000  5.000000  5.000000


In [21]:
print(csvfile_1.head(2))
print()
print(csvfile_1.tail(2))
print()
print(csvfile_1[1:3])
print()
print(csvfile_1.to_numpy())

   First  Second  Third
0      1       1      1
1      2       2      2

   First  Second  Third
3      4       4      4
4      5       5      5

   First  Second  Third
1      2       2      2
2      3       3      3

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


In [22]:
import numpy as np
v = np.asarray(csvfile_1)
print(v)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]]


In [23]:
csvfile_1.sort_index(axis=0, ascending=False)

First  Second  Third
4      5       5      5
3      4       4      4
2      3       3      3
1      2       2      2
0      1       1      1

In [24]:
csvfile_1.loc[0,"First"] = "Python"
print(csvfile_1)
print()
csvfile_1.loc[[1,2],["First","Second"]]


    First  Second  Third
0  Python       1      1
1       2       2      2
2       3       3      3
3       4       4      4
4       5       5      5



C:\Users\Riddhi\AppData\Local\Temp\ipykernel_2440\1499672123.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Python' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  csvfile_1.loc[0,"First"] = "Python"


First  Second
1     2       2
2     3       3

In [25]:
#csvfile_1.drop("First",axis=1)
csvfile_1.drop(0,axis=0)

First  Second  Third
1     2       2      2
2     3       3      3
3     4       4      4
4     5       5      5

In [26]:
#var.dropna()  removes null values
#parameters if needed are axis, how, subset, inplace, thresh
#var.fillna()  fills null values 
#parameters if needed are axis, inplace, limit, method = "ffill"/"bfill"

In [28]:
csvfile_2 = pd.read_csv("D:\\Data Analytst\pandas\\text_new1.csv")
print(csvfile_2)

   First  Second  Third
0      1       1      1
1      2       2      2
2      3       3      3
3      4       4      4
4      5       5      5


In [36]:
csvfile_2.replace(to_replace=3, value=13)
#csvfile_2.replace(["A-Z"], "python", regex = True)  now we don't have alphabets

C:\Users\Riddhi\AppData\Local\Temp\ipykernel_2440\255218746.py:1: FutureWarning: The 'limit' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csvfile_2.replace(to_replace=3, value=13, limit=1)


First  Second  Third
0      1       1      1
1      2       2      2
2     13      13     13
3      4       4      4
4      5       5      5

In [35]:
csvfile_2.replace(13,method="bfill" ,limit=1) #achese kam kyu nhi karra pata nhi

C:\Users\Riddhi\AppData\Local\Temp\ipykernel_2440\3266704615.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csvfile_2.replace(13,method="bfill" ,limit=1)


First  Second  Third
0      1       1      1
1      2       2      2
2      3       3      3
3      4       4      4
4      5       5      5

In [ ]:
#var.interpolate() replace null values automatically
#it works only with numbers and not with alphabets